# Generated by Django 3.0.4 on 2020-07-21 02:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectspost',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 2, 11, 53, 477083, tzinfo=utc)),
        ),
    ]
