# Generated by Django 3.0.4 on 2020-07-21 03:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200721_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectspost',
            name='picture',
        ),
        migrations.AlterField(
            model_name='projectspost',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
