# Generated by Django 3.0.4 on 2020-07-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200721_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectspost',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='projects-pics'),
        ),
    ]
