# Generated by Django 3.0.4 on 2020-07-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_projectspost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectspost',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/projects/projects'),
        ),
    ]
